# This is a basic workflow to help you get started with Actions

name: CI - Playground runner
description: 'Build and run all Xcode Playgrounds in a repository'
author: 'Matt Hanlon <@mhanlon>'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

runs:
  using: "composite"
  steps:
    - id: xcode-playground-runner
    run: sh $GITHUB_ACTION_PATH/verifyPlaygrounds.sh
    shell: bash
