# This is a basic workflow to help you get started with Actions

name: CI - Playground runner
description: 'Build and run all Xcode Playgrounds in a repository'
author: 'Matt Hanlon <@mhanlon>'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    runs:
      using: "composite"
      steps:
        - run: sh $GITHUB_ACTION_PATH/verifyPlaygrounds.sh
        - shell: bash
