# This is a basic workflow to help you get started with Actions

name: CI - Playground runner

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the script to cd into each playground, build it (and its subpages) and run it
      - name: Build and run Xcode Playgrounds
        run: sh ${{ github.action_path }}/verifyPlaygrounds.sh
